root: true
env:
    node: true
parser: '@typescript-eslint/parser'
parserOptions:
    project: './tsconfig.json'
plugins:
    - '@typescript-eslint'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
rules:
    'no-constant-condition':
        - off
        - checkLoops: false
    '@typescript-eslint/no-non-null-assertion': off
    '@typescript-eslint/explicit-module-boundary-types': off
    'prefer-const': warn
    'eqeqeq':
        - error
        - always
    eol-last:
        - error
        - always
    '@typescript-eslint/no-floating-promises':
        - warn
    '@typescript-eslint/no-unused-vars':
        - warn
        - argsIgnorePattern: ^_$
    'no-empty-function':
        - off
    '@typescript-eslint/no-namespace': off
    '@typescript-eslint/no-empty-function': off
    no-empty:
        - error
        - allowEmptyCatch: true
overrides:
    - files: "*.js"
      parser: espree
      parserOptions:
            ecmaVersion: 2021
