name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '15' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('./{package.json,pnpm-lock.yaml}') }}
      - name: install dependencies
        run: npm install
      - name: build package
        run: npm run prepublishOnly
      - name: run tests
        run: npm run test
